# version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: agency-postgres
    environment:
      POSTGRES_DB: agency
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: